In [1]:
include("ppn.jl")
using .PrimePlaceNotation

In [2]:
using Printf

for n in 1:12
    @printf("%2u & %11s & %2u & %11s & %2u & %11s \\\\\n", n, to_ppn(n), n+12, to_ppn(n+12), n+24, to_ppn(n+24))
end

 1 &           0 & 13 &      100000 & 25 &         200 \\
 2 &           1 & 14 &        1001 & 26 &      100001 \\
 3 &          10 & 15 &         110 & 27 &          30 \\
 4 &           2 & 16 &           4 & 28 &        1002 \\
 5 &         100 & 17 &     1000000 & 29 &  1000000000 \\
 6 &          11 & 18 &          21 & 30 &         111 \\
 7 &        1000 & 19 &    10000000 & 31 & 10000000000 \\
 8 &           3 & 20 &         102 & 32 &           5 \\
 9 &          20 & 21 &        1010 & 33 &       10010 \\
10 &         101 & 22 &       10001 & 34 &     1000001 \\
11 &       10000 & 23 &   100000000 & 35 &        1100 \\
12 &          12 & 24 &          13 & 36 &          22 \\

In [8]:
for n in 1:1023
    x = to_ppn(n)
    length(x) == 5 && @printf("%8s\t%4u\n", to_ppn(n), n)
end

   10000	  11
   10001	  22
   10010	  33
   10002	  44
   10100	  55
   10011	  66
   11000	  77
   10003	  88
   10020	  99
   10101	 110
   20000	 121
   10012	 132
   11001	 154
   10110	 165
   10004	 176
   10021	 198
   10102	 220
   11010	 231
   20001	 242
   10013	 264
   10200	 275
   10030	 297
   11002	 308
   10111	 330
   10005	 352
   20010	 363
   11100	 385
   10022	 396
   10103	 440
   11011	 462
   20002	 484
   10120	 495
   10014	 528
   12000	 539
   10201	 550
   10031	 594
   20100	 605
   11003	 616
   10112	 660
   11020	 693
   10006	 704
   20011	 726
   11101	 770
   10023	 792
   10210	 825
   21000	 847
   10104	 880
   10040	 891
   11012	 924
   20003	 968
   10121	 990

In [4]:
for n in 1:99
    @printf("%25s\t%2u\n", to_ppn(n), n)
end

                        0	 1
                        1	 2
                       10	 3
                        2	 4
                      100	 5
                       11	 6
                     1000	 7
                        3	 8
                       20	 9
                      101	10
                    10000	11
                       12	12
                   100000	13
                     1001	14
                      110	15
                        4	16
                  1000000	17
                       21	18
                 10000000	19
                      102	20
                     1010	21
                    10001	22
                100000000	23
                       13	24
                      200	25
                   100001	26
                       30	27
                     1002	28
               1000000000	29
                      111	30
              10000000000	31
                        5	32
                    10010	33
                  1000001	34
                     1100	35
                       22	36
             100000000000	37
                 10000001	38
                   100010	39
                      103	40
            1000000000000	41
                     1011	42
           10000000000000	43
                    10002	44
                      120	45
                100000001	46
          100000000000000	47
                       14	48
                     2000	49
                      201	50
                  1000010	51
                   100002	52
         1000000000000000	53
                       31	54
                    10100	55
                     1003	56
                 10000010	57
               1000000001	58
        10000000000000000	59
                      112	60
       100000000000000000	61
              10000000001	62
                     1020	63
                        6	64
                   100100	65
                    10011	66
      1000000000000000000	67
                  1000002	68
                100000010	69
                     1101	70
     10000000000000000000	71
                       23	72
    100000000000000000000	73
             100000000001	74
                      210	75
                 10000002	76
                    11000	77
                   100011	78
   1000000000000000000000	79
                      104	80
                       40	81
            1000000000001	82
  10000000000000000000000	83
                     1012	84
                  1000100	85
           10000000000001	86
               1000000010	87
                    10003	88
 100000000000000000000000	89
                      121	90
                   101000	91
                100000002	92
              10000000010	93
          100000000000001	94
                 10000100	95
                       15	96
1000000000000000000000000	97
                     2001	98
                    10020	99

In [5]:
parse_ppn(to_ppn(72))

72

In [9]:
parse_ppn("10114")

2640